"""empty message

Revision ID: 7ebd812b9758
Revises: 832b79138cc0
Create Date: 2020-12-04 09:36:28.579008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebd812b9758'
down_revision = '832b79138cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('APP_USER', sa.Column('username', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'APP_USER', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'APP_USER', type_='unique')
    op.drop_column('APP_USER', 'username')
    # ### end Alembic commands ###
