"""empty message

Revision ID: bfdb5feb0ca6
Revises: 54e47658d1f4
Create Date: 2020-12-03 21:47:46.147192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfdb5feb0ca6'
down_revision = '54e47658d1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('APP_USER', sa.Column('discription', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'APP_USER', ['discription'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'APP_USER', type_='unique')
    op.drop_column('APP_USER', 'discription')
    # ### end Alembic commands ###
