"""empty message

Revision ID: f2504eddab48
Revises: bfdb5feb0ca6
Create Date: 2020-12-03 22:10:24.620860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2504eddab48'
down_revision = 'bfdb5feb0ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('discription', table_name='APP_USER')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('discription', 'APP_USER', ['discription'], unique=True)
    # ### end Alembic commands ###
